[package]
name = "bit7z-rt-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-rt-ipc = { path = "../ipc" }
bit7z-app-archive = { path = "../../application/archive" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true

