[package]
name = "bit7z-pres-dialogs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-pres-settings = { path = "../settings" }
bit7z-pres-components = { path = "../components" }
bit7z-app-archive = { path = "../../application/archive" }
bit7z-infra-platform = { path = "../../infrastructure/platform" }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
crossbeam-channel = { workspace = true }
humansize = { workspace = true }

