[package]
name = "bit7z-rt-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-app-archive = { path = "../../application/archive" }
bit7z-infra-persistence = { path = "../../infrastructure/persistence" }
clap = { version = "4", features = ["derive"] }
humansize = "2"

