[package]
name = "bit7z-rt-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-rt-globals = { path = "../globals" }
bit7z-pres-theme = { path = "../../presentation/theme" }
bit7z-pres-view-models = { path = "../../presentation/view-models" }
bit7z-pres-views = { path = "../../presentation/views" }
bit7z-pres-components = { path = "../../presentation/components" }
bit7z-infra-bit7z = { path = "../../infrastructure/bit7z" }
bit7z-infra-persistence = { path = "../../infrastructure/persistence" }
bit7z-infra-platform = { path = "../../infrastructure/platform" }
bit7z-infra-tray = { path = "../../infrastructure/tray" }
bit7z-infra-events = { path = "../../infrastructure/events" }
bit7z-rt-ipc = { path = "../ipc" }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["runtime_shaders"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
crossbeam = "0.8"
anyhow = "1"
