[package]
name = "bit7z-domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
secrecy = { version = "0.10", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1"
