[package]
name = "bit7z-domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
secrecy = { version = "0.10", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { workspace = true }

[features]
testing = []
