[package]
name = "bit7z-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cross-platform compressed file viewer and editor"

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-infra-bit7z = { path = "../../infrastructure/bit7z" }
bit7z-infra-persistence = { path = "../../infrastructure/persistence" }
bit7z-infra-platform = { path = "../../infrastructure/platform" }
bit7z-rt-ipc = { path = "../ipc" }
bit7z-rt-worker = { path = "../worker" }
bit7z-rt-cli = { path = "../cli" }
bit7z-rt-gui = { path = "../gui" }
clap = { version = "4", features = ["derive"] }
