[package]
name = "bit7z-pres-view-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-infra-events = { path = "../../infrastructure/events" }
bit7z-infra-tray = { path = "../../infrastructure/tray" }
bit7z-infra-progress = { path = "../../infrastructure/progress" }
gpui = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5"
