[package]
name = "bit7z-pres-components"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
ui_macros.workspace = true
component.workspace = true
