[package]
name = "bit7z-pres-components"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-pres-theme = { path = "../theme" }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
serde = { version = "1", features = ["derive"] }
smallvec = "1.15.2"
