[package]
name = "bit7z-rt-app-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bit7z-domain = { path = "../../domain" }
bit7z-infra-tray = { path = "../../infrastructure/tray" }
bit7z-infra-persistence = { path = "../../infrastructure/persistence" }
bit7z-rt-ipc = { path = "../ipc" }
fs = { path = "../../application/fs" }
gpui = { workspace = true }
anyhow.workspace = true
crossbeam-channel = "0.5"
